### ISSUE TITLE
Request: MultiWorld support?

### ISSUE THREAD

**Issue by AryToNeX** [Heromine/FloatingTexter#4]
Can you add multiworld support?

**Comment by Heromine** [comment]
Soon

**Comment by DunxGit** [comment]
When you add multiworld support does that also mean we could add multiple texts in ONE world/

**Comment by Heromine** [comment]
@DunxGit why not? multiple texts in many worlds

**Comment by DunxGit** [comment]
OK, Sounds cool :)

**Comment by TahaTheHacker** [comment]
actually. Dunxit you can use LiveSigns by aliuly instead.until an update comes in this :)

**Comment by PIANOCRAFT6000** [comment]
@Heromine how can I add more text is it like this? 


---
text: example
text1: example
text2: example
coords:
  x: 131
  "y": 108
  z: 127

text: example
text1: example
text2: example
coords:
  x: 131
  "y": 108
  z: 127
...

**Comment by TahaTheHacker** [comment]
heromine, i can help you doing this plugin !

**Comment by dunxgit** [comment]
Heromine has actually quite MCPE.

**Comment by AryToNeX** [comment]
I did it. @Heromine please merge

**Comment by Heromine** [comment]
Thanks to @AryToNeX
